Repository typegoose/mongodb-memory-server, pull requests merged in 2020-09, with the labels that each got.

#353 fix(package): move non-exposed @types to devDependencies
  packages/mongodb-memory-server-core/package.json
Labels: dependencies

#352 docs(README): fix mentions of "latest" while being "4.0.14"
  README.md
Labels: docs

#360 fix(MongoBinaryDownload): print used URL in 404 Error
  packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts
Labels: enhancement

#371 fix(Dependencies): update mongodb version
  package.json
  packages/mongodb-memory-server-core/package.json
  yarn.lock
Labels: dependencies

#368 fix(MongoMemoryReplSet): comment-out older hack
  packages/mongodb-memory-server-core/src/MongoMemoryReplSet.ts
Labels: enhancement

#372 fix(postinstall): skip postinstall if "SYSTEM_BINARY" is set
  packages/mongodb-memory-server-global-3.4/postinstall.js
  packages/mongodb-memory-server-global-3.6/postinstall.js
  packages/mongodb-memory-server-global-4.0/postinstall.js
  packages/mongodb-memory-server-global-4.2/postinstall.js
  packages/mongodb-memory-server-global-4.4/postinstall.js
  packages/mongodb-memory-server-global/postinstall.js
  packages/mongodb-memory-server/postinstall.js
Labels: enhancement

#376 build: fix yarn.lock & resolve yarn warnings
  package.json
  packages/mongodb-memory-server-core/package.json
  yarn.lock
Labels: dependencies

#375 fix(MongoBinary): improve code
  .eslintignore
  .vscode/settings.json
  package.json
  packages/mongodb-memory-server-core/package.json
  packages/mongodb-memory-server-core/src/util/MongoBinary.ts
  packages/mongodb-memory-server-core/src/util/__tests__/MongoBinary-test.ts
  yarn.lock
Labels: enhancement

#377 fix(resolve-config): improve code
  README.md
  packages/mongodb-memory-server-core/src/util/MongoBinary.ts
  packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts
  packages/mongodb-memory-server-core/src/util/__tests__/resolve-config-test.ts
  packages/mongodb-memory-server-core/src/util/resolve-config.ts
  yarn.lock
Labels: enhancement

#382 docs: fix contributing guide location in readme
  README.md
Labels: docs

#383 feat: skip binary download when binary tar exists
  packages/mongodb-memory-server-core/src/util/MongoBinaryDownload.ts
  packages/mongodb-memory-server-core/src/util/__tests__/MongoBinaryDownload-test.ts
Labels: feature

#386 explicitly export default from mms
  packages/mongodb-memory-server-global-3.4/index.js
  packages/mongodb-memory-server-global-3.6/index.js
  packages/mongodb-memory-server-global-4.0/index.js
  packages/mongodb-memory-server-global-4.2/index.js
  packages/mongodb-memory-server-global-4.4/index.js
  packages/mongodb-memory-server-global/index.js
  packages/mongodb-memory-server/index.js
Labels: enhancement
